{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api
{{- end }}