{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtmc.fullname" . }}-api
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "rtmc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "rtmc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.api.env.aspnetcoreEnvironment | quote }}
        - name: ConnectionStrings__DefaultConnection
          value: "Host={{ include "rtmc.fullname" . }}-postgres;Port={{ .Values.postgres.service.port }};Database={{ .Values.postgres.auth.database }};Username={{ .Values.postgres.auth.username }};Password={{ .Values.postgres.auth.password }}"
        - name: Redis__ConnectionString
          value: "{{ include "rtmc.fullname" . }}-redis:{{ .Values.redis.service.port }}"
        - name: Kafka__BootstrapServers
          value: "{{ include "rtmc.fullname" . }}-kafka:{{ .Values.kafka.service.port }}"
        - name: RabbitMQ__HostName
          value: "{{ include "rtmc.fullname" . }}-rabbitmq"
        - name: RabbitMQ__UserName
          value: {{ .Values.rabbitmq.auth.username | quote }}
        - name: RabbitMQ__Password
          value: {{ .Values.rabbitmq.auth.password | quote }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
