{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtmc.fullname" . }}-grafana
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rtmc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "rtmc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.auth.username | quote }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.auth.password | quote }}
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel"
        - name: GF_SERVER_ROOT_URL
          value: "http://localhost/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        {{- if .Values.grafana.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
      {{- if .Values.grafana.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "rtmc.fullname" . }}-grafana-pvc
      {{- end }}
{{- end }}