{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtmc.fullname" . }}-grafana
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "rtmc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}