{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtmc.fullname" . }}-rabbitmq
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
  - port: {{ .Values.rabbitmq.service.port }}
    targetPort: amqp
    protocol: TCP
    name: amqp
  - port: {{ .Values.rabbitmq.service.managementPort }}
    targetPort: management
    protocol: TCP
    name: management
  selector:
    {{- include "rtmc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
