{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtmc.fullname" . }}-elasticsearch
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rtmc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: elasticsearch
  template:
    metadata:
      labels:
        {{- include "rtmc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: {{ .Values.elasticsearch.auth.password | quote }}
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        {{- if .Values.elasticsearch.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        {{- end }}
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: http
            httpHeaders:
            - name: Authorization
              value: Basic {{ printf "elastic:%s" .Values.elasticsearch.auth.password | b64enc }}
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
            httpHeaders:
            - name: Authorization
              value: Basic {{ printf "elastic:%s" .Values.elasticsearch.auth.password | b64enc }}
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
      {{- if .Values.elasticsearch.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "rtmc.fullname" . }}-elasticsearch-pvc
      {{- end }}
{{- end }}