{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rtmc.fullname" . }}-elasticsearch-pvc
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.elasticsearch.persistence.storageClass }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
{{- end }}