{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtmc.fullname" . }}-kafka
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: kafka
    protocol: TCP
    name: kafka
  selector:
    {{- include "rtmc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
{{- end }}
