{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtmc.fullname" . }}-redis
  labels:
    {{- include "rtmc.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "rtmc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
